### ISSUE TITLE
Errors following flashing instructions

### ISSUE THREAD

**Issue by karnlund** [bluzDK/particle-gateway-shield-code#2]
The flashing instructions from README.md cause the following errors:

$ particle flash IATBluzGatewayPhoton particle-gateway-code.cpp
Including:
    particle-gateway-code.cpp
attempting to flash firmware to your device IATBluzGatewayPhoton
Flash device failed
particle-gateway-code.cpp:39:12: error: expected constructor, destructor, or type conversion before '(' token
 SYSTEM_MODE(SEMI_AUTOMATIC);
            ^
particle-gateway-code.cpp:59:5: error: 'TCPClient' does not name a type
     TCPClient socket;
     ^
particle-gateway-code.cpp:65:17: error: variable or field 'debugPrint' declared void
 void debugPrint(String msg) {
                 ^
particle-gateway-code.cpp:65:17: error: 'String' was not declared in this scope
particle-gateway-code.cpp:69:1: error: 'String' does not name a type
 String gatewayID = "No gateway detected yet.";
 ^
particle-gateway-code.cpp:74:25: error: variable or field 'handle_custom_data' declared void
 void handle_custom_data(uint8_t _data, int length) {
                         ^
particle-gateway-code.cpp:74:25: error: 'uint8_t' was not declared in this scope
particle-gateway-code.cpp:74:34: error: 'data' was not declared in this scope
 void handle_custom_data(uint8_t *data, int length) {
                                  ^
particle-gateway-code.cpp:74:40: error: expected primary-expression before 'int'
 void handle_custom_data(uint8_t *data, int length) {
                                        ^
particle-gateway-code.cpp: In function 'void setup()':
particle-gateway-code.cpp:84:5: error: 'Particle' was not declared in this scope
     Particle.variable("gatewayID", gatewayID);
     ^
particle-gateway-code.cpp:84:36: error: 'gatewayID' was not declared in this scope
     Particle.variable("gatewayID", gatewayID);
                                    ^
particle-gateway-code.cpp:13:22: error: 'A2' was not declared in this scope
 #define SLAVE_SELECT A2
                      ^
particle-gateway-code.cpp:86:13: note: in expansion of macro 'SLAVE_SELECT'
     pinMode(SLAVE_SELECT, OUTPUT);
             ^
particle-gateway-code.cpp:86:27: error: 'OUTPUT' was not declared in this scope
     pinMode(SLAVE_SELECT, OUTPUT);
                           ^
particle-gateway-code.cpp:86:33: error: 'pinMode' was not declared in this scope
     pinMode(SLAVE_SELECT, OUTPUT);
                                 ^
particle-gateway-code.cpp:87:32: error: 'HIGH' was not declared in this scope
     digitalWrite(SLAVE_SELECT, HIGH);
                                ^
particle-gateway-code.cpp:87:36: error: 'digitalWrite' was not declared in this scope
     digitalWrite(SLAVE_SELECT, HIGH);
                                    ^
particle-gateway-code.cpp:89:5: error: 'SPI' was not declared in this scope
     SPI.begin();
     ^
particle-gateway-code.cpp:90:21: error: 'LSBFIRST' was not declared in this scope
     SPI.setBitOrder(LSBFIRST);
                     ^
particle-gateway-code.cpp:91:25: error: 'SPI_CLOCK_DIV128' was not declared in this scope
     SPI.setClockDivider(SPI_CLOCK_DIV128);
                         ^
particle-gateway-code.cpp:92:21: error: 'SPI_MODE0' was not declared in this scope
     SPI.setDataMode(SPI_MODE0);
                     ^
particle-gateway-code.cpp:94:30: error: 'INPUT_PULLDOWN' was not declared in this scope
     pinMode(SLAVE_ALERT_PIN, INPUT_PULLDOWN);
                              ^
particle-gateway-code.cpp:1:23: error: 'TX' was not declared in this scope
 #define SLAVE_PTS_PIN TX
                       ^
particle-gateway-code.cpp:95:13: note: in expansion of macro 'SLAVE_PTS_PIN'
     pinMode(SLAVE_PTS_PIN, INPUT_PULLDOWN);
             ^
particle-gateway-code.cpp:2:26: error: 'RX' was not declared in this scope
 #define MASTER_READY_PIN RX
                          ^
particle-gateway-code.cpp:97:13: note: in expansion of macro 'MASTER_READY_PIN'
     pinMode(MASTER_READY_PIN, OUTPUT);
             ^
particle-gateway-code.cpp:98:36: error: 'LOW' was not declared in this scope
     digitalWrite(MASTER_READY_PIN, LOW);
                                    ^
particle-gateway-code.cpp:100:5: error: 'Serial' was not declared in this scope
     Serial.begin(38400);
     ^
particle-gateway-code.cpp:101:27: error: 'debugPrint' was not declared in this scope
     debugPrint("STARTING!");
                           ^
particle-gateway-code.cpp: In function 'void requestID()':
particle-gateway-code.cpp:110:5: error: 'uint8_t' was not declared in this scope
     uint8_t dummy[6] = {(( (6-SPI_HEADER_SIZE-BLE_HEADER_SIZE) & 0xFF00) >> 8), ( (6-SPI_HEADER_SIZE-BLE_HEADER_SIZE) & 0xFF), MAX_CLIENTS-1, INFO_DATA_SERVICE, 0, 0};
     ^
particle-gateway-code.cpp:110:13: error: expected ';' before 'dummy'
     uint8_t dummy[6] = {(( (6-SPI_HEADER_SIZE-BLE_HEADER_SIZE) & 0xFF00) >> 8), ( (6-SPI_HEADER_SIZE-BLE_HEADER_SIZE) & 0xFF), MAX_CLIENTS-1, INFO_DATA_SERVICE, 0, 0};
             ^
particle-gateway-code.cpp:111:14: error: 'dummy' was not declared in this scope
     spi_send(dummy, 6);
              ^
particle-gateway-code.cpp:111:22: error: 'spi_send' was not declared in this scope
     spi_send(dummy, 6);
                      ^
particle-gateway-code.cpp: At global scope:
particle-gateway-code.cpp:116:17: error: 'uint8_t' was not declared in this scope
 char hexToAscii(uint8_t byte)
                 ^
particle-gateway-code.cpp:117:1: error: expected ',' or ';' before '{' token
 {
 ^
particle-gateway-code.cpp:122:33: error: 'uint8_t' has not been declared
 void parseID(char *destination, uint8_t *buffer)
                                 ^
particle-gateway-code.cpp: In function 'void parseID(char_, int_)':
particle-gateway-code.cpp:126:76: error: 'hexToAscii' cannot be used as a function
         destination[gatewayIndex++] = hexToAscii( ((buffer[i] >> 4) & 0xF) );
                                                                            ^
particle-gateway-code.cpp:127:69: error: 'hexToAscii' cannot be used as a function
         destination[gatewayIndex++] = hexToAscii( (buffer[i] & 0xF) );
                                                                     ^
particle-gateway-code.cpp: At global scope:
particle-gateway-code.cpp:132:23: error: variable or field 'spi_data_process' declared void
 void spi_data_process(uint8_t *buffer, uint16_t length, uint8_t clientId)
                       ^
particle-gateway-code.cpp:132:23: error: 'uint8_t' was not declared in this scope
particle-gateway-code.cpp:132:32: error: 'buffer' was not declared in this scope
 void spi_data_process(uint8_t *buffer, uint16_t length, uint8_t clientId)
                                ^
particle-gateway-code.cpp:132:40: error: 'uint16_t' was not declared in this scope
 void spi_data_process(uint8_t *buffer, uint16_t length, uint8_t clientId)
                                        ^
particle-gateway-code.cpp:132:57: error: 'uint8_t' was not declared in this scope
 void spi_data_process(uint8_t *buffer, uint16_t length, uint8_t clientId)
                                                         ^
make[1]: *_\* [../build/target/user/platform-6particle-gateway-code.o] Error 1
make: **\* [user] Error 2

**Comment by eely22** [comment]
The code has been modified into a Particle Library and the instructions have been changed to reflect such.
